spring:
  ai:
    vectorstore:
      milvus:
        client:
          host: ${VDB_URL}
          port: ${VDB_PORT}
          username: ${VDB_USER}
          password: ${VDB_PASSWORD}
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
    openai:
      api-key: ${OPENAI_API_KEY}
    retry:
      max-attempts: 1
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/conversation
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  dataimport:
    enabled: true

